In [ ]:
#finding min max

In [11]:
import numpy as np
a=np.array([[0,1],[2,3]])
print("max",np.amax(a))
print("min",np.amin(a))

max 3
min 0


#reshaping array

In [14]:
x=np.arange(4)
x.reshape(2,2)

array([[0, 1],
       [2, 3]])

 Write a NumPy program to calculate the difference between the maximum and the minimum values of a given array along the second axis. 
 Original array:
[[ 0 1 2 3 4 5]
[ 6 7 8 9 10 11]]
Difference between the maximum and the minimum values of the said array:
[5 5]

In [25]:
a=np.arange(12)
a=a.reshape(2,6)
np.amax(a,axis=1)-np.amin(a,axis=1)

array([5, 5])

Write a NumPy program to compute the 80th percentile for all elements in a given array along the second axis. Go to the editor
Expected Output:
Original array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

80th percentile for all elements of the said array along the second axis:
[ 4. 10.]

In [29]:
a=np.arange(12)
a=a.reshape(2,6)
print("percentile",np.percentile(a,80,axis=1))

percentile [ 4. 10.]


In [31]:
print("median",np.median(a))

median 5.5


Write a NumPy program to compute the mean, standard deviation, and variance of a given array along the second axis. Go to the editor
Sample output:
Original array:
[0 1 2 3 4 5]
Mean: 2.5
std: 1
variance: 2.9166666666666665

In [32]:
a=np.arange(6)
print(np.mean(a))
print(np.std(a))
print(np.var(a))

2.5
1.707825127659933
2.9166666666666665


Write a Python program to count number of occurrences of each value in a given array of non-negative integers.

In [34]:
import numpy as np
a=np.arange(9)
np.bincount(a)

array([1, 1, 1, 1, 1, 1, 1, 1, 1])